#!/usr/bin/env python3
"""
Generate ticker_map.hpp from tickers.json.
Uses frozen library for compile-time perfect hash map.
All functions are inline, no .cpp needed.
"""

import json
import argparse
import sys
from pathlib import Path

def generate_ticker_map(input_path, output_hpp_path, ticker_size=4):
    try:
        with open(input_path, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: File not found: {input_path}")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON: {e}")
        sys.exit(1)
    
    tickers_data = data.get('tickers', [])
    entries = []
    for item in tickers_data:
        ticker = item.get('ticker', '')
        if ticker:
            entries.append(ticker)
    
    if not entries:
        print("Warning: No tickers found, using fallback")
        entries = ["UNKN"]
    
    Path(output_hpp_path).parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_hpp_path, 'w') as f:
        f.write("// Auto-generated by generate_ticker_map.py\n")
        f.write("// DO NOT EDIT MANUALLY\n\n")
        f.write("#pragma once\n\n")
        f.write("#include <array>\n")
        f.write("#include <string_view>\n")
        f.write("#include <frozen/unordered_map.h>\n")
        f.write("#include <frozen/string.h>\n\n")
        f.write('#include "ticker.hpp"\n\n')
        f.write("namespace hft {\n\n")
        
        f.write(f"inline constexpr size_t TICKER_COUNT = {len(entries)};\n\n")
        
        # Массив имен как frozen::string для точного соответствия
        f.write("inline constexpr std::array<std::string_view, TICKER_COUNT> TICKER_NAMES = {{\n")
        for ticker in entries:
            f.write(f'    "{ticker}",\n')
        f.write("}};\n\n")
        
        # Карта frozen::string -> int
        f.write("// Perfect hash map, built at compile-time\n")
        f.write("inline constexpr auto TICKER_MAP = frozen::make_unordered_map<frozen::string, int>({\n")
        for i, ticker in enumerate(entries):
            f.write(f'    {{"{ticker}", {i}}},\n')
        f.write("});\n\n")
        
        # --- Перегрузки для std::string_view ---
        f.write("inline int getTickerIndex(std::string_view ticker) noexcept {\n")
        f.write("    auto it = TICKER_MAP.find(ticker);\n")
        f.write("    if (it != TICKER_MAP.end()) {\n")
        f.write("        return it->second;\n")
        f.write("    }\n")
        f.write("    return -1;\n")
        f.write("}\n\n")
        
        # --- Перегрузка для Ticker (array<char, 4>) ---
        f.write("inline int getTickerIndex(const Ticker& ticker) noexcept {\n")
        f.write("    std::string_view sv(ticker.data(), ticker.size());\n")
        f.write("    return getTickerIndex(sv);\n")
        f.write("}\n\n")
        
        # --- Функция для получения Ticker по индексу ---
        f.write("inline Ticker getTicker(uint32_t index) noexcept {\n")
        f.write("    Ticker ticker{};\n")
        f.write("    if (index < TICKER_COUNT) {\n")
        f.write("        const auto& name = TICKER_NAMES[index];\n")
        f.write("        const size_t len = name.size();\n")
        f.write("        const size_t copy_len = (len < ticker.size()) ? len : ticker.size();\n")
        f.write("        for (size_t i = 0; i < copy_len; ++i) {\n")
        f.write("            ticker[i] = name[i];\n")
        f.write("        }\n")
        f.write("        // Остальные байты уже zero-initialized\n")
        f.write("    }\n")
        f.write("    return ticker;\n")
        f.write("}\n\n")

        # --- Функция для отладки ---
        f.write("inline std::string_view getTickerName(uint32_t index) noexcept {\n")
        f.write('    return TICKER_NAMES[index];\n')
        f.write("}\n\n")
        
        f.write("} // namespace hft\n")
    
    print(f"✅ Generated {output_hpp_path} with {len(entries)} tickers")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', required=True)
    parser.add_argument('--output-hpp', required=True)
    args = parser.parse_args()
    generate_ticker_map(args.input, args.output_hpp)

if __name__ == "__main__":
    main()